version: '3.1'

services:

  db:
    container_name: asp.netBlogDB
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: blogDB
    ports: 
      - "5432:5432"